'use strict';

const SURVEY_TYPES = Object.freeze(['QUARTERLY', 'MOVE_OUT']);
const SURVEY_STATUSES = Object.freeze(['DRAFT', 'ACTIVE', 'CLOSED', 'ARCHIVED']);
const RESPONSE_STATUSES = Object.freeze(['DRAFT', 'SUBMITTED']);
const TENANT_RESPONSE_STATUSES = Object.freeze(['NOT_STARTED', 'IN_PROGRESS', 'SUBMITTED', 'EXPIRED', 'NOT_ELIGIBLE']);
const RECOMMENDATION_VALUES = Object.freeze(['YES', 'NO', 'MAYBE']);
const MOVE_OUT_REASONS = Object.freeze([
  'CONTRACT_COMPLETED', 'TRANSFERRED_LOCATION', 'WORK_OR_SCHOOL_CHANGE',
  'FINANCIAL_REASON', 'ROOM_OR_FACILITY_CONCERN', 'SERVICE_CONCERN',
  'PERSONAL_REASON', 'OTHER',
]);
const RATING_CATEGORIES = Object.freeze([
  'OVERALL_SATISFACTION', 'ROOM_CONDITION', 'CLEANLINESS', 'STAFF_ASSISTANCE',
  'MAINTENANCE_RESPONSE', 'SECURITY', 'INTERNET_CONNECTION',
  'FACILITIES_COMMON_AREAS', 'VALUE_FOR_MONEY',
]);

module.exports = {
  MOVE_OUT_REASONS,
  RATING_CATEGORIES,
  RECOMMENDATION_VALUES,
  RESPONSE_STATUSES,
  SURVEY_STATUSES,
  SURVEY_TYPES,
  TENANT_RESPONSE_STATUSES,
};
