// Room Transfer error vocabulary from the September 15 QA inventory.
const MESSAGES = {
  "Preferred transfer date is invalid.": "Choose a valid date that is today or later in Manila and falls within the current lease. If the date is confirmed already, ask administration to reschedule it.",
  "Preferred transfer date must be today or later.": "Choose a valid date that is today or later in Manila and falls within the current lease. If the date is confirmed already, ask administration to reschedule it.",
  "A valid active stay is required to view room preferences.": "A room transfer cannot proceed with the current stay details. Ask administration to review the tenant\u2019s stay, room assignment, and lease before trying again.",
  "Only active tenants may request a room transfer.": "Room transfers are available to current residents. Contact administration if you are living here but cannot submit a request.",
  "Reason is required.": "Tell administration why you would like to change rooms.",
  "A valid active stay is required to request a room transfer.": "A room transfer cannot proceed with the current stay details. Ask administration to review the tenant\u2019s stay, room assignment, and lease before trying again.",
  "Current stay details are unavailable.": "A room transfer cannot proceed with the current stay details. Ask administration to review the tenant\u2019s stay, room assignment, and lease before trying again.",
  "Only active moved-in tenants may request a room transfer.": "A room transfer cannot proceed with the current stay details. Ask administration to review the tenant\u2019s stay, room assignment, and lease before trying again.",
  "Resolve the pending stay extension first.": "A stay extension or renewal is already in progress. Ask administration to resolve it before requesting a room transfer.",
  "A room transfer is already scheduled for this tenancy.": "Your room transfer is already scheduled. Open its details or contact administration if you need a change.",
  "You already have an open room transfer request.": "You already have an active room transfer request. Please wait for it to be resolved before submitting another request.",
  "Room transfer is unavailable because move-out clearance has started.": "A room transfer cannot proceed with the current stay details. Ask administration to review the tenant\u2019s stay, room assignment, and lease before trying again.",
  "Room transfer is unavailable during an active termination review.": "A room transfer cannot proceed with the current stay details. Ask administration to review the tenant\u2019s stay, room assignment, and lease before trying again.",
  "Your current lease Contract is not eligible for a room transfer.": "A room transfer cannot proceed with the current stay details. Ask administration to review the tenant\u2019s stay, room assignment, and lease before trying again.",
  "Preferred transfer date cannot be after your current lease end date.": "Choose a valid date that is today or later in Manila and falls within the current lease. If the date is confirmed already, ask administration to reschedule it.",
  "Preferred room is invalid.": "Choose a supported room type and a preferred room in your current branch. Administration will confirm availability.",
  "Preferred room must be different from your current room.": "Choose a supported room type and a preferred room in your current branch. Administration will confirm availability.",
  "Preferred room is unavailable for this branch.": "Choose a supported room type and a preferred room in your current branch. Administration will confirm availability.",
  "Preferred room does not match the selected room type.": "Choose Private, Double Sharing, or Quadruple Sharing, then select a preferred room that matches that type.",
  "Room transfer request not found.": "We could not find this tenant\u2019s room transfer record. Refresh the page and open the tenant again.",
  "Only a pending room transfer request can be cancelled.": "This request can no longer be changed here because its status has changed. Refresh its details and contact administration if you need help.",
  "This request already has an operational room transfer.": "This tenant already has an active room transfer. Open the existing request to review its status before creating another.",
  "This request is no longer pending or is already being scheduled.": "This tenant already has an active room transfer. Open the existing request to review its status before creating another.",
  "Room transfer request not found for your branch.": "We could not find this tenant\u2019s room transfer record. Refresh the page and open the tenant again.",
  "Only a pending, unscheduled request can be declined.": "This request can no longer be changed here because its status has changed. Refresh its details and contact administration if you need help.",
  "The operational transfer was created, but its request link needs reconciliation.": "We could not complete this room transfer action. Refresh its status and try again; contact administration if it still fails.",
  "A verified canonical security deposit is already recorded; a manual override is not allowed.": "Review the tenant\u2019s deposit receipt and enter the amount currently held, along with the source of that information, before continuing.",
  "Verify the tenant's recorded security deposit through payment/deposit records before completing the transfer.": "Review the tenant\u2019s deposit receipt and enter the amount currently held, along with the source of that information, before continuing.",
  "Enter a valid verified security deposit amount.": "Review the tenant\u2019s deposit receipt and enter the amount currently held, along with the source of that information, before continuing.",
  "Confirm that the amount was verified against the tenant's payment/deposit records.": "Review the tenant\u2019s deposit receipt and enter the amount currently held, along with the source of that information, before continuing.",
  "A verification source, reason, and authenticated admin are required for a deposit override.": "Enter a short explanation so administration or the tenant understands this request or decision.",
  "Review the pending stay extension request first.": "A stay extension or renewal is already in progress. Ask administration to resolve it before requesting a room transfer.",
  "Room transfer is blocked because move-out clearance has started.": "A room transfer cannot proceed with the current stay details. Ask administration to review the tenant\u2019s stay, room assignment, and lease before trying again.",
  "Room transfer is blocked by an active termination review.": "A room transfer cannot proceed with the current stay details. Ask administration to review the tenant\u2019s stay, room assignment, and lease before trying again.",
  "A future renewal already exists for this tenant. Resolve or cancel it before transferring.": "A future lease renewal is already in progress. Ask administration to resolve it before transferring.",
  "applyScheduledTransferHold requires a transaction session": "We could not complete this room transfer action. Refresh its status and try again; contact administration if it still fails.",
  "The destination room is full.": "The selected room or bed is no longer available. Refresh the available rooms and choose another destination.",
  "A destination bed is required to hold a shared room.": "Choose an available bed in the selected shared room to continue.",
  "Destination bed not found in the room.": "The selected room or bed is no longer available. Refresh the available rooms and choose another destination.",
  "The selected destination bed is not available.": "The selected room or bed is no longer available. Refresh the available rooms and choose another destination.",
  "releaseScheduledTransferHold requires a transaction session": "We could not complete this room transfer action. Refresh its status and try again; contact administration if it still fails.",
  "The scheduled destination bed hold no longer matches this transfer.": "The selected room or bed is no longer available. Refresh the available rooms and choose another destination.",
  "The effective transfer date cannot be in the past.": "Choose a valid date that is today or later in Manila and falls within the current lease. If the date is confirmed already, ask administration to reschedule it.",
  "This tenant already has a scheduled room transfer. Cancel it before scheduling another.": "This tenant already has an active room transfer. Open the existing request to review its status before creating another.",
  "This tenant already has a scheduled room transfer.": "This tenant already has an active room transfer. Open the existing request to review its status before creating another.",
  "No open scheduled room transfer to reschedule.": "We could not complete this room transfer action. Refresh its status and try again; contact administration if it still fails.",
  "This room transfer has already been completed.": "We could not complete this room transfer action. Refresh its status and try again; contact administration if it still fails.",
  "This room transfer is currently being completed and cannot be rescheduled.": "We could not complete this room transfer action. Refresh its status and try again; contact administration if it still fails.",
  "A new effective transfer date is required.": "Choose a valid date that is today or later in Manila and falls within the current lease. If the date is confirmed already, ask administration to reschedule it.",
  "The new effective transfer date cannot be in the past.": "Choose a valid date that is today or later in Manila and falls within the current lease. If the date is confirmed already, ask administration to reschedule it.",
  "The reserved destination bed is no longer held for this transfer. Cancel and re-schedule.": "The selected room or bed is no longer available. Refresh the available rooms and choose another destination.",
  "This room transfer changed while it was being rescheduled.": "We could not complete this room transfer action. Refresh its status and try again; contact administration if it still fails.",
  "A paid or partially paid transfer cannot be rescheduled automatically.": "This transfer bill already has a payment. Ask administration to review the financial difference before changing the schedule.",
  "The Room Transfer Addendum is missing or already current.": "We could not complete this room transfer action. Refresh its status and try again; contact administration if it still fails.",
  "The Room Transfer Addendum has already been acknowledged or signed and cannot be rescheduled silently.": "The tenant has already accepted this addendum. Ask administration to arrange a reviewed replacement before changing the schedule.",
  "The scheduled transfer changed before the reschedule could commit.": "We could not complete this room transfer action. Refresh its status and try again; contact administration if it still fails.",
  "No scheduled room transfer to complete for this tenant.": "We could not complete this room transfer action. Refresh its status and try again; contact administration if it still fails.",
  "The reserved destination bed is no longer available for this transfer. Review the destination room.": "The selected room or bed is no longer available. Refresh the available rooms and choose another destination.",
  "The destination room no longer exists.": "This request can no longer be changed here because its status has changed. Refresh its details and contact administration if you need help.",
  "The destination room is over capacity.": "The selected room or bed is no longer available. Refresh the available rooms and choose another destination.",
  "Enter the current (closing) electricity meter reading of the tenant's current room before completing the transfer.": "Enter the current meter reading for the named room. It must be zero or higher and must not be below the previous recorded reading. Review any missing readings with administration.",
  "Enter the current electricity meter reading of the destination room \u2014 it becomes the tenant's opening baseline there.": "Enter the current meter reading for the named room. It must be zero or higher and must not be below the previous recorded reading. Review any missing readings with administration.",
  "The transfer settlement could not be computed. Review the tenant's billing/lease state.": "Open the linked transfer bill to review the balance and payment status. Complete any required payment before retrying the transfer; ask administration to review adjustments or refunds.",
  "Another Complete Transfer request is already executing.": "Another administrator is completing this transfer. Wait briefly, then refresh its status.",
  "This scheduled transfer no longer has a consumable destination hold.": "This request can no longer be changed here because its status has changed. Refresh its details and contact administration if you need help.",
  "Reservation not found": "We could not find this tenant\u2019s room transfer record. Refresh the page and open the tenant again.",
  "Only active moved-in tenants can be transferred.": "A room transfer cannot proceed with the current stay details. Ask administration to review the tenant\u2019s stay, room assignment, and lease before trying again.",
  "Transfer confirmation is required.": "We could not complete this room transfer action. Refresh its status and try again; contact administration if it still fails.",
  "Target room is required.": "Select an available destination room to continue.",
  "Target room not found.": "The selected room or bed is no longer available. Refresh the available rooms and choose another destination.",
  "Transfers are limited to rooms within the same branch.": "We could not complete this room transfer action. Refresh its status and try again; contact administration if it still fails.",
  "A specific bed must be selected for a shared room.": "Choose an available bed in the selected shared room to continue.",
  "Target bed not found in the destination room.": "The selected room or bed is no longer available. Refresh the available rooms and choose another destination.",
  "No active stay found for transfer.": "A room transfer cannot proceed with the current stay details. Ask administration to review the tenant\u2019s stay, room assignment, and lease before trying again.",
  "The tenant's current lease Contract is not active \u2014 room transfer cannot proceed.": "A room transfer cannot proceed with the current stay details. Ask administration to review the tenant\u2019s stay, room assignment, and lease before trying again.",
  "Transfer target must differ from the current room and bed.": "The selected room or bed is no longer available. Refresh the available rooms and choose another destination.",
  "No current Contract for this tenant.": "A room transfer cannot proceed with the current stay details. Ask administration to review the tenant\u2019s stay, room assignment, and lease before trying again.",
  "This Room Transfer has already been completed and cannot be discarded here. Post-cutover reversal is a separate workflow.": "We could not complete this room transfer action. Refresh its status and try again; contact administration if it still fails.",
  "No prepared Room Transfer Addendum to discard.": "We could not complete this room transfer action. Refresh its status and try again; contact administration if it still fails.",
  "The tenant's current approved rent cannot be verified. Review the active Stay, current Contract, and Reservation pricing before preparing the Addendum.": "A room transfer cannot proceed with the current stay details. Ask administration to review the tenant\u2019s stay, room assignment, and lease before trying again.",
  "The rebuilt Room Transfer Addendum still does not match the approved room, bed, effective date, or rate.": "Choose a valid date that is today or later in Manila and falls within the current lease. If the date is confirmed already, ask administration to reschedule it.",
  "This Complete Transfer request no longer owns the scheduled hold.": "This request can no longer be changed here because its status has changed. Refresh its details and contact administration if you need help.",
  "Current room not found.": "We could not find this tenant\u2019s room transfer record. Refresh the page and open the tenant again.",
  "Selected target bed is not available.": "The selected room or bed is no longer available. Refresh the available rooms and choose another destination.",
  "The prepared replacement Contract does not match the selected destination room.": "A room transfer cannot proceed with the current stay details. Ask administration to review the tenant\u2019s stay, room assignment, and lease before trying again.",
  "The room-transfer replacement Contract changed between preparation and execution. Retry the transfer.": "A room transfer cannot proceed with the current stay details. Ask administration to review the tenant\u2019s stay, room assignment, and lease before trying again.",
  "The destination room filled up before the transfer could complete.": "We could not complete this room transfer action. Refresh its status and try again; contact administration if it still fails.",
  "A fresh source-room closing electricity reading is required.": "Enter the current meter reading for the named room. It must be zero or higher and must not be below the previous recorded reading. Review any missing readings with administration.",
  "The tenant's current approved rent cannot be verified. Review the active Stay, current Contract, and Reservation pricing before transferring.": "A room transfer cannot proceed with the current stay details. Ask administration to review the tenant\u2019s stay, room assignment, and lease before trying again.",
  "The first-period advance payment cannot be verified. Review the initial payment before transferring this tenant.": "Open the linked transfer bill to review the balance and payment status. Complete any required payment before retrying the transfer; ask administration to review adjustments or refunds.",
  "The prepared Room Transfer Addendum does not match the selected destination bed.": "The selected room or bed is no longer available. Refresh the available rooms and choose another destination.",
  "The prepared Room Transfer Addendum has no valid approved destination rate.": "We could not complete this room transfer action. Refresh its status and try again; contact administration if it still fails.",
  "The tenant's actual security deposit held cannot be verified. Review payment/deposit records before transferring.": "Review the tenant\u2019s deposit receipt and enter the amount currently held, along with the source of that information, before continuing.",
  "The linked Scheduled Room Transfer Balance Bill is missing or invalid.": "Open the linked transfer bill to review the balance and payment status. Complete any required payment before retrying the transfer; ask administration to review adjustments or refunds.",
  "The Scheduled Room Transfer Balance Bill no longer matches the canonical settlement recomputed at execution.": "Open the linked transfer bill to review the balance and payment status. Complete any required payment before retrying the transfer; ask administration to review adjustments or refunds.",
  "The scheduled destination hold could not be consumed atomically.": "We could not complete this room transfer action. Refresh its status and try again; contact administration if it still fails.",
  "One or both reservations not found for room swap": "We could not find this tenant\u2019s room transfer record. Refresh the page and open the tenant again.",
  "Direct room swap cannot be executed across different branches. Use standard tenant transfer.": "We could not complete this room transfer action. Refresh its status and try again; contact administration if it still fails.",
  "Only moved-in tenants can be transferred.": "We could not complete this room transfer action. Refresh its status and try again; contact administration if it still fails.",
  "No cancellable scheduled room transfer for this tenant.": "This request can no longer be changed here because its status has changed. Refresh its details and contact administration if you need help.",
  "This room transfer has already been completed and cannot be cancelled here.": "This request can no longer be changed here because its status has changed. Refresh its details and contact administration if you need help.",
  "No open scheduled room transfer for this tenant.": "We could not complete this room transfer action. Refresh its status and try again; contact administration if it still fails.",
  "This scheduled transfer needs Administration-Office settlement before it can be retried.": "Open the linked transfer bill to review the balance and payment status. Complete any required payment before retrying the transfer; ask administration to review adjustments or refunds.",
  "Pick a new effective date of today or later.": "Choose a valid date that is today or later in Manila and falls within the current lease. If the date is confirmed already, ask administration to reschedule it.",
  "Enter a valid transfer time (HH:mm).": "Enter a valid transfer time, such as 09:00.",
  "The source room reading must be a finite, non-negative number.": "Enter the current meter reading for the named room. It must be zero or higher and must not be below the previous recorded reading. Review any missing readings with administration.",
  "The destination room reading must be a finite, non-negative number.": "Enter the current meter reading for the named room. It must be zero or higher and must not be below the previous recorded reading. Review any missing readings with administration.",
  "Enter the verified security deposit currently held.": "Review the tenant\u2019s deposit receipt and enter the amount currently held, along with the source of that information, before continuing.",
  "Confirm the records review and enter its source and reason.": "Enter a short explanation so administration or the tenant understands this request or decision.",
  "Pick an effective date of today or later.": "Choose a valid date that is today or later in Manila and falls within the current lease. If the date is confirmed already, ask administration to reschedule it.",
  "Please pick a transfer time.": "We could not complete this room transfer action. Refresh its status and try again; contact administration if it still fails.",
  "Settlement preview is still loading \u2014 please wait.": "The settlement preview is loading. Wait for the amounts to appear before continuing.",
  "Failed to generate settlement receipt PDF.": "The settlement receipt could not be downloaded. Try again; contact administration if it still fails.",
  "Choose a destination room first.": "We could not complete this room transfer action. Refresh its status and try again; contact administration if it still fails.",
  "Please make sure all transfer details are valid.": "We could not complete this room transfer action. Refresh its status and try again; contact administration if it still fails.",
  "Select a preferred room type and enter a reason.": "Choose Private, Double Sharing, or Quadruple Sharing, then select a preferred room that matches that type.",
  "Use a valid date in YYYY-MM-DD format that is today or later.": "Choose a valid date that is today or later in Manila and falls within the current lease. If the date is confirmed already, ask administration to reschedule it."
};
export function getRoomTransferError(error, fallback = "We couldn't process your room transfer right now. Please refresh its status and try again.") {
  const data = error?.response?.data;
  const status = error?.response?.status || error?.statusCode;
  const raw = typeof error === 'string' ? error : data?.detail || data?.error?.message || data?.error || data?.message || error?.message || '';
  const text = typeof raw === 'string' ? raw : '';
  if (status === 401) return 'Your session has expired. Sign in again to continue.';
  if (/network|timeout|ECONN|failed to fetch/i.test(text) || error?.code === 'ERR_NETWORK') return "We couldn't confirm your request because of a connection problem. Check your internet connection, then refresh its status before trying again.";
  if (/E11000|duplicate key/i.test(text)) return 'This transfer may already have been saved. Refresh its status before trying again.';
  if (/API route not found|Server error|AxiosError|MongoServerError|CastError|ValidationError|ReferenceError|TypeError|ObjectId|[a-f0-9]{24}|undefined|\[object Object\]|\bat \w+.*\(|status code \d+|action_required|awaiting_settlement|scheduledRoomTransfer/i.test(text)) return fallback;
  if (Number(status) >= 500) return fallback;
  if (MESSAGES[text]) return MESSAGES[text];
  if (text && text.length < 600 && !/error:|stack|Mongo|invalid.*id format/i.test(text)) return text;
  if (status === 403) return 'This room transfer action is unavailable for your account. Contact administration for assistance.';
  if (status === 409) return 'The room transfer status has changed. Refresh its details before trying again.';
  if (status === 422 || status === 400) return 'Some transfer details need review. Check your entries and try again.';
  return fallback;
}
